#!/usr/bin/env bash

set -euo pipefail

INSTALL_MARKER="/etc/cp/.npm_openappsec_installed"
ADVANCED_MODEL="/advanced-model/open-appsec-advanced-model.tgz"
WATCHDOG_PID=""
WATCHDOG_LOG="/var/log/nano_agent/watchdog.log"

mkdir -p /etc/cp/conf /etc/cp/data /var/log/nano_agent /ext/appsec /dev/shm/check-point

install_agent_if_needed() {
    if [ -f "${INSTALL_MARKER}" ]; then
        return
    fi

    orchestration_args=(--install --container_mode --skip_registration --hybrid_mode)

    if [ -n "${AGENT_TOKEN:-}" ]; then
        orchestration_args+=(--token "${AGENT_TOKEN}")
    fi

    /nano-service-installers/install-cp-nano-agent.sh "${orchestration_args[@]}"
    /nano-service-installers/install-cp-nano-attachment-registration-manager.sh --install
    /nano-service-installers/install-cp-nano-agent-cache.sh --install
    /nano-service-installers/install-cp-nano-service-http-transaction-handler.sh --install

    touch "${INSTALL_MARKER}"
}

# Generate /data/nginx/custom/http_top.conf with CrowdSec bouncer wiring when
# CROWDSEC_BOUNCER_URL is set and the file does not already exist.
#
# The generated file contains:
#   - An 'upstream crowdsec_bouncer' block pointing at CROWDSEC_BOUNCER_URL.
#   - A 'map $host $crowdsec_skip' block pre-populated from CROWDSEC_SKIP_HOSTS.
#
# CROWDSEC_BOUNCER_URL  — host:port of the crowdsec-bouncer container
#                         (default: crowdsec-bouncer:8080 when the env var is set).
# CROWDSEC_SKIP_HOSTS   — optional comma-separated list of hostnames to exclude from
#                         CrowdSec checks (e.g. "internal.example.com,webhook.example.com").
#                         Only applied on initial file generation. To add exclusions
#                         later, edit the map block in the generated file directly.
#
# If /data/nginx/custom/http_top.conf already exists the function does nothing so
# manual edits to the file are never overwritten.
configure_crowdsec_http_top() {
    local bouncer_url="${CROWDSEC_BOUNCER_URL:-}"
    local skip_hosts="${CROWDSEC_SKIP_HOSTS:-}"
    local http_top="/data/nginx/custom/http_top.conf"

    # Only generate when the user has opted in by setting CROWDSEC_BOUNCER_URL.
    if [ -z "${bouncer_url}" ]; then
        return
    fi

    if [ -f "${http_top}" ]; then
        echo "[open-appsec-agent] CrowdSec: ${http_top} already exists — skipping auto-generation."
        echo "[open-appsec-agent] CrowdSec: to modify host exclusions, edit the map block in that file directly."
        return
    fi

    mkdir -p /data/nginx/custom

    # Build the map entries from the comma-separated CROWDSEC_SKIP_HOSTS list.
    local map_entries=""
    if [ -n "${skip_hosts}" ]; then
        local IFS=","
        for host in ${skip_hosts}; do
            # Trim leading/trailing whitespace.
            host="$(echo "${host}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [ -n "${host}" ]; then
                map_entries="${map_entries}    \"${host}\"    1; # CROWDSEC_SKIP_HOSTS\n"
            fi
        done
    fi

    cat > "${http_top}" << NGINX_CONF
# CrowdSec bouncer wiring — auto-generated by start-openappsec-agent on first start.
# Edit this file to change settings. It will not be regenerated while it exists.
# See examples/crowdsec-snippets/http_top.conf for the full annotated template.
#
# To exclude additional hosts from CrowdSec checks, add entries to the map block:
#   "example.com"    1;
# To enable per-proxy-host protection, add the contents of
# examples/crowdsec-snippets/proxy-host-advanced.conf to each NPM proxy host's
# "Advanced" configuration textarea in the NPM UI.

# Map used to skip CrowdSec checks for specific virtual-host names.
# Value 1 = skip check; default 0 = check all hosts.
map \$host \$crowdsec_skip {
    default 0;
$(echo -e "${map_entries}")    # Add more exclusions here:
    # "internal.example.com"    1;
}

# Upstream: crowdsec-bouncer HTTP forwardAuth service (IP ban checks).
upstream crowdsec_bouncer {
    server ${bouncer_url};
    keepalive 32;
}

# Optional: CrowdSec AppSec upstream (header-based WAF inspection).
# Uncomment after installing crowdsecurity/appsec-virtual-patching and
# crowdsecurity/appsec-generic-rules inside the crowdsec container.
# upstream crowdsec_appsec {
#     server crowdsec:7422;
#     keepalive 32;
# }
NGINX_CONF

    echo "[open-appsec-agent] CrowdSec: generated ${http_top} (bouncer: ${bouncer_url})"
    if [ -n "${skip_hosts}" ]; then
        echo "[open-appsec-agent] CrowdSec: skip hosts configured: ${skip_hosts}"
    fi
}

start_watchdog() {
    touch /etc/cp/watchdog/wd.startup
    /etc/cp/watchdog/cp-nano-watchdog >>"${WATCHDOG_LOG}" 2>&1 &
    WATCHDOG_PID="$!"
}

cleanup() {
    if [ -n "${WATCHDOG_PID}" ] && ps -p "${WATCHDOG_PID}" >/dev/null 2>&1; then
        kill -TERM "${WATCHDOG_PID}" 2>/dev/null || true
        wait "${WATCHDOG_PID}" 2>/dev/null || true
    fi
}

trap cleanup SIGTERM SIGINT

install_agent_if_needed

if [ -f "${ADVANCED_MODEL}" ]; then
    mkdir -p /etc/cp/conf/waap
    tar -xzf "${ADVANCED_MODEL}" -C /etc/cp/conf/waap
fi

configure_crowdsec_http_top

start_watchdog

while true; do
    # Trigger file used by open-appsec runtime components when watchdog-managed services are upgraded
    # or reconfigured and require a clean watchdog restart to reload processes.
    if [ -f /tmp/restart_watchdog ]; then
        rm -f /tmp/restart_watchdog
        kill -TERM "${WATCHDOG_PID}" 2>/dev/null || true
        wait "${WATCHDOG_PID}" 2>/dev/null || true
        WATCHDOG_PID=""
    fi

    if [ -z "${WATCHDOG_PID}" ] || ! ps -p "${WATCHDOG_PID}" >/dev/null 2>&1; then
        start_watchdog
    fi

    sleep 5
done
