#!/usr/bin/env bash

set -euo pipefail

INSTALL_MARKER="/etc/cp/.npm_openappsec_installed"
ADVANCED_MODEL="/advanced-model/open-appsec-advanced-model.tgz"
WATCHDOG_PID=""
WATCHDOG_LOG="/var/log/nano_agent/watchdog.log"

mkdir -p /etc/cp/conf /etc/cp/data /var/log/nano_agent /ext/appsec /dev/shm/check-point

install_agent_if_needed() {
    if [ -f "${INSTALL_MARKER}" ]; then
        return
    fi

    orchestration_args=(--install --container_mode --skip_registration --hybrid_mode)

    if [ -n "${AGENT_TOKEN:-}" ]; then
        orchestration_args+=(--token "${AGENT_TOKEN}")
    fi

    /nano-service-installers/install-cp-nano-agent.sh "${orchestration_args[@]}"
    /nano-service-installers/install-cp-nano-attachment-registration-manager.sh --install
    /nano-service-installers/install-cp-nano-agent-cache.sh --install
    /nano-service-installers/install-cp-nano-service-http-transaction-handler.sh --install

    touch "${INSTALL_MARKER}"
}

istrue() {
    case "${1:-}" in
        1|true|TRUE|True|yes|YES|Yes|on|ON|On) return 0 ;;
        *) return 1 ;;
    esac
}

write_crowdsec_server_conf() {
    local output_path="$1"
    local mode_comment='Requests are inspected by CrowdSec AppSec over its built-in HTTP endpoint.'

    cat > "${output_path}" << NGINX_CONF
# CrowdSec protection — auto-generated by start-openappsec-agent on first start.
# Edit this file to change settings. It will not be regenerated while it exists.
# ${mode_comment}
#
# To exclude a host manually, edit /data/nginx/custom/http_top.conf and add it to
# the map block below, or set CROWDSEC_SKIP_HOSTS=host1.example.com,host2.example.com
# before the first container start so the map is pre-populated automatically.

location = /crowdsec-check {
    internal;
    auth_request off;

    # Host exclusions are driven from the map in http_top.conf. This nginx "if"
    # only performs an immediate return, which is one of the safe nginx if usages.
    if (\$crowdsec_skip) {
        return 204;
    }

    proxy_pass http://crowdsec_appsec/;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-URI \$request_uri;
    proxy_set_header X-Forwarded-Method \$request_method;
}

auth_request /crowdsec-check;
error_page 401 403 = @crowdsec_deny;

location @crowdsec_deny {
    internal;
    auth_request off;
    return 403 "Access denied.\n";
}
NGINX_CONF
}

# Generate the nginx custom include files needed for a compose-only CrowdSec setup.
# When CROWDSEC_ENABLED=true, the script creates:
#   - /data/nginx/custom/http_top.conf
#   - /data/nginx/custom/server_proxy.conf
#   - /data/nginx/custom/server_redirect.conf
# if they do not already exist. Existing files are never overwritten.
#
# CROWDSEC_SKIP_HOSTS is a comma-separated list of hostnames to exclude from the
# generated auth_request flow. To add or remove exclusions later, edit the map in
# /data/nginx/custom/http_top.conf manually.
configure_crowdsec_nginx() {
    local crowdsec_enabled="${CROWDSEC_ENABLED:-false}"
    local appsec_url="${CROWDSEC_APPSEC_URL:-crowdsec:7422}"
    local skip_hosts="${CROWDSEC_SKIP_HOSTS:-}"
    local http_top="/data/nginx/custom/http_top.conf"
    local server_proxy="/data/nginx/custom/server_proxy.conf"
    local server_redirect="/data/nginx/custom/server_redirect.conf"

    if ! istrue "${crowdsec_enabled}"; then
        return
    fi

    mkdir -p /data/nginx/custom

    local map_entries=""
    if [ -n "${skip_hosts}" ]; then
        local IFS=","
        for host in ${skip_hosts}; do
            host="$(echo "${host}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [ -n "${host}" ]; then
                map_entries="${map_entries}    \"${host}\"    1; # CROWDSEC_SKIP_HOSTS\n"
            fi
        done
    fi

    if [ ! -f "${http_top}" ]; then
        cat > "${http_top}" << NGINX_CONF
# CrowdSec wiring — auto-generated by start-openappsec-agent on first start.
# Edit this file to change settings. It will not be regenerated while it exists.
#
# To exclude a host manually, add it to the map below:
#   "internal.example.com"    1;
# To populate exclusions declaratively on first start, set:
#   CROWDSEC_SKIP_HOSTS=internal.example.com,webhook.example.com
# This setup uses CrowdSec's built-in AppSec endpoint directly, so no separate
# bouncer sidecar is required.

map \$host \$crowdsec_skip {
    default 0;
$(echo -e "${map_entries}")    # Add more exclusions here if needed:
    # "internal.example.com"    1;
}

upstream crowdsec_appsec {
    server ${appsec_url};
    keepalive 32;
}
NGINX_CONF
        echo "[open-appsec-agent] CrowdSec: generated ${http_top}"
    else
        echo "[open-appsec-agent] CrowdSec: ${http_top} already exists — keeping manual configuration."
    fi

    if [ ! -f "${server_proxy}" ]; then
        write_crowdsec_server_conf "${server_proxy}"
        echo "[open-appsec-agent] CrowdSec: generated ${server_proxy}"
    else
        echo "[open-appsec-agent] CrowdSec: ${server_proxy} already exists — keeping manual configuration."
    fi

    if [ ! -f "${server_redirect}" ]; then
        write_crowdsec_server_conf "${server_redirect}"
        echo "[open-appsec-agent] CrowdSec: generated ${server_redirect}"
    else
        echo "[open-appsec-agent] CrowdSec: ${server_redirect} already exists — keeping manual configuration."
    fi
}

start_watchdog() {
    touch /etc/cp/watchdog/wd.startup
    /etc/cp/watchdog/cp-nano-watchdog >>"${WATCHDOG_LOG}" 2>&1 &
    WATCHDOG_PID="$!"
}

cleanup() {
    if [ -n "${WATCHDOG_PID}" ] && ps -p "${WATCHDOG_PID}" >/dev/null 2>&1; then
        kill -TERM "${WATCHDOG_PID}" 2>/dev/null || true
        wait "${WATCHDOG_PID}" 2>/dev/null || true
    fi
}

trap cleanup SIGTERM SIGINT

install_agent_if_needed

if [ -f "${ADVANCED_MODEL}" ]; then
    mkdir -p /etc/cp/conf/waap
    tar -xzf "${ADVANCED_MODEL}" -C /etc/cp/conf/waap
fi

configure_crowdsec_nginx

start_watchdog

while true; do
    # Trigger file used by open-appsec runtime components when watchdog-managed services are upgraded
    # or reconfigured and require a clean watchdog restart to reload processes.
    if [ -f /tmp/restart_watchdog ]; then
        rm -f /tmp/restart_watchdog
        kill -TERM "${WATCHDOG_PID}" 2>/dev/null || true
        wait "${WATCHDOG_PID}" 2>/dev/null || true
        WATCHDOG_PID=""
    fi

    if [ -z "${WATCHDOG_PID}" ] || ! ps -p "${WATCHDOG_PID}" >/dev/null 2>&1; then
        start_watchdog
    fi

    sleep 5
done
